
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0004:Certificate Validation has been disabled", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.BackupController.RunBackup")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Logging.LogService.CreateLogAsync(System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Logging.LogService.LogEventAsync(System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Logging.LogService.LogSmtpErrorAsync(System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Services.ArchiveService.CreateArchivesAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Services.FtpService.UploadFileAsync(System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Services.SmtpService.CreateSmtpMessgeAsync~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Services.UploadService.UploadBackupFilesAsync(ServerBackupUtility.Services.IFtpService)~System.Threading.Tasks.Task")]

