
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Logging.LogService.CreateLog(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Logging.LogService.LogEvent(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Logging.LogService.LogSmtpError(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Services.ArchiveService.CreateArchives")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Services.SmtpService.CreateSmtpMessge~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Services.SmtpService.CreateSmtpMessge")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Services.UploadService.UploadBackupFiles(ServerBackupUtility.Services.IFtpService)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0004:Certificate Validation has been disabled", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.BackupController.RunBackup")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Services.DatabaseService.BackupDatabases(ServerBackupUtility.Services.IFtpService)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "SCS0018:Path traversal: injection possible in {1} argument passed to '{0}'", Justification = "<Pending>", Scope = "member", Target = "~M:ServerBackupUtility.Services.FtpService.UploadFile(System.String)")]

